name: Spring Boot CI

# Sproži se ob push ali pull request na main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v3

      # Namesti JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Cache Maven dependencies za hitrejši build
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build projekta
      - name: Build with Maven
        run: mvn clean install --batch-mode
        working-directory: Backend

      # Poženi teste
      - name: Run tests
        run: mvn test
        working-directory: Backend
