name: Spring Boot Unit Tests

# Sproži se ob push ali pull request na main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Namesti JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Poganjaj samo enote teste in izključi contextLoads test
      - name: Run unit tests
        run: mvn -f Backend/pom.xml -DskipTests=false -Dtest='!StranZaRecepteApplicationTests' test
